/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Misclases.Mesa;
import java.sql.SQLException;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marce
 */
public class VentanaBuscarMesaCalificaciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaBuscarMesa
     */
    public VentanaBuscarMesaCalificaciones() throws SQLException {
        initComponents();
        actualizartabla("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jtbuscar = new javax.swing.JTextField();
        jBsalir = new javax.swing.JButton();

        setClosable(true);
        setTitle("BUSCAR MESAS DE EXAMENES");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "BUSCAR MATERIA"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel11.setText("MATERIA");

        jtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbuscarActionPerformed(evt);
            }
        });
        jtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtbuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtbuscarKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jBsalir.setText("SALIR");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(jBsalir)
                .addContainerGap(431, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(389, Short.MAX_VALUE)
                .addComponent(jBsalir)
                .addGap(24, 24, 24))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            int filaselec = this.jTable1.getSelectedRow();
            InterfazCalificaciones.jTidmesa.setText(this.jTable1.getValueAt(filaselec, 0).toString());
            int id_mesa = Integer.parseInt((String) this.jTable1.getValueAt(filaselec, 0));
            Mesa mesa_selecionada = new Mesa();
            mesa_selecionada = Principal.escuela.gme.buscarMesa(id_mesa);
            InterfazCalificaciones.actualizartabla2(mesa_selecionada);
            InterfazCalificaciones.jTfecha.setText(this.jTable1.getValueAt(filaselec, 3).toString());
            String curso_selecionado = Integer.toString(mesa_selecionada.materia.curso);
            InterfazCalificaciones.jTcurso.setText(curso_selecionado);
            InterfazCalificaciones.jTmateria.setText(mesa_selecionada.materia.nombre.trim());
            InterfazCalificaciones.jTcondicion.setText(mesa_selecionada.condicion.trim());
            InterfazCalificaciones.jTpresidente.setText(mesa_selecionada.tribunal.presidente.apellido.trim() + " " + mesa_selecionada.tribunal.presidente.nombre.trim());
            InterfazCalificaciones.jTvocal1.setText(mesa_selecionada.tribunal.vocal1.apellido.trim() + " " + mesa_selecionada.tribunal.vocal1.nombre.trim());
            InterfazCalificaciones.jTvocal2.setText(mesa_selecionada.tribunal.vocal2.apellido.trim() + " " + mesa_selecionada.tribunal.vocal2.nombre.trim());
            InterfazCalificaciones.jThora.setText(this.jTable1.getValueAt(filaselec, 4).toString());
            InterfazCalificaciones.jtflibro.setEditable(true);
            InterfazCalificaciones.jtffolio.setEditable(true);
            InterfazCalificaciones.jtflibro.setText("0");
            InterfazCalificaciones.jtffolio.setText("0");
            InterfazCalificaciones.jBCerrarMesa.setEnabled(true);
            InterfazCalificaciones.jBactualizaCalificacion.setEnabled(true);
            InterfazCalificaciones.jTable2.setEnabled(true);
            InterfazCalificaciones.mesa_selecionada = mesa_selecionada;
        } catch (SQLException ex) {
            Logger.getLogger(VentanaBuscarMesaCalificaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbuscarActionPerformed

    private void jtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbuscarKeyReleased
        try {
            actualizartabla(this.jtbuscar.getText().trim());
        } catch (SQLException ex) {
            Logger.getLogger(InterfazDocente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtbuscarKeyReleased

    private void jtbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbuscarKeyTyped

    }//GEN-LAST:event_jtbuscarKeyTyped

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBsalirActionPerformed
    private void actualizartabla(String a) throws SQLException {
        ArrayList<Mesa> lm = Principal.escuela.gme.listarMesa(a);
        Iterator<Mesa> itrusu = lm.iterator();
        Integer contador;
        contador = 0;
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("CURSO");
        modelo.addColumn("MATERIA");
        modelo.addColumn("FECHA");
        modelo.addColumn("HORA");
        modelo.addColumn("CONDICION");
        while (itrusu.hasNext()) {
            itrusu.next();
            String fila[] = new String[6];
            fila[0] = Integer.toString(lm.get(contador).id);
            fila[1] = Integer.toString(lm.get(contador).materia.curso);
            fila[2] = lm.get(contador).materia.nombre;
            Format formatter = new SimpleDateFormat("dd/MM/yyyy");
            fila[3] = formatter.format(lm.get(contador).fecha);
            fila[4] = String.valueOf(lm.get(contador).horario);
            fila[5] = lm.get(contador).condicion;
            modelo.addRow(fila);
            contador++;
        }
        this.jTable1.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtbuscar;
    // End of variables declaration//GEN-END:variables
}
